### ISSUE TITLE
Does this project support msvc?

### ISSUE THREAD

**Issue by liuziangexit** [nokiatech/heif#11]

**Comment by lixo6500** [comment]
I was able to build it using Visual Studio 2015 (Update 2).

The only problem (well, not really a problem, but I really do not like it) is that building this library generates thousands of warnings, 99.999% of them due to missing type casts.  Fortunately most of them can be easily fixed by doing some adjusts in the BitStream class.

The other 0.001% warnings were that (questionable and infamous)  C4800, which can also be easily fixed.

Other than that, and that you will need an external library in order to be able to decode the images/videos, you should be good to go.

**Comment by liuziangexit** [comment]
thx, i just use cmake successfully build it.

**Comment by fjhub** [comment]
I've been using cmake to build this project on my Mac and have been able to successfully run some tests without too many roadblocks.  I decided to build things with VS1025 using cmake on my Windows 7 machine.

After getting things to build, I discovered that my test application did not give me the same results as my application on the Mac.  After some investigation, I discovered that the raw (compressed) data from my Windows application did not match that from my Mac application.  Hence the differing results.

Just curious if you were able to get something reasonable working using VS2015.

Next step is to try to debug both apps at the same time and compare data on the two platforms to see if I can figure out where things are going bad on Windows.  Maybe it has something to do with one (or more) of the large number of compilation warnings.

**Comment by liuziangexit** [comment]
but i dont have a mac...

**Comment by fjhub** [comment]
Not sure how to interpret your comment.  When I say that my Windows build didn't give me the same results, it was obvious that the results were incorrect.

Did you get things to work correctly with your Windows build?  If so, was it out of the box or after fixing the warnings or other modifications?

I'm in the process of fixing the warnings...some of which I cannot believe...so hopefully addressing them will resolve the issue of the raw (compressed) data not matching.

**Comment by fjhub** [comment]
ouch...just realized that the data I was saving on Windows was not binary which explains the difference.  all is good now that I fixed this rookie mistake.

**Comment by liuziangexit** [comment]
lolololol that was funny.
