### ISSUE TITLE
corrupted tile in grid

### ISSUE THREAD

**Issue by Kimbsen** [nokiatech/heif#9]
I'm having trouble converting HEIC files from an iphone to a jpeg. The files contain 8x6 grids of images and every file, apart from some inputs, such as panorama shots(not 8x6 grid) have the 7th tile corrupted. 

see attached file: 
![final](https://user-images.githubusercontent.com/1135327/28923132-3f58e12c-785d-11e7-8876-cebd8b20ba1c.jpg)

I put some code in a github repo: https://github.com/Kimbsen/heiftest to reproduce the problem. the code there is pretty self explanatory.

Any ideas what i might be doing wrong? I've excluded rotating the image though it should have been rotated 270 degrees as the problem is present regardless.

**Comment by shuoli84** [comment]
I just met the same problem, and got some clue. But still working on a fix.
1) 
The reason why it is corrupted is: It is using a wrong sps config to decode the tile 7. 

2) Why it is using a wrong sps? 
What I found is, There are 2 sets of decode params inside the heif file, one for the grids, and one for thumb (I guess). The place to set mParameterSetMap using key [contextId, hvccIndex]. But the place to retrieve the params actually using [contextId, itemId]. 
Then why other tiles looks ok? Because there is a fallback logic in getDecoderParameterSets, when there is no result found, then it use mImageToParameterSetMap, which maps [contextId, itemId] => [contextId, hvccIndex], which returns the correct parameter.

3) How to fix?
For what I see, just always use mImageToParameterSetMap as a quick fix. But I don't know the behind reason why the original logic, so need more test.

**Comment by nokiatech** [comment]
Resolved by v3.0
